#!/bin/sh

# Check if PHPUnit is available in the project
if [ -f ./vendor/bin/phpunit ]; then
    # Check if Paratest is available in the project
    if [ -f ./vendor/bin/paratest ]; then
        ./vendor/bin/paratest
    else
        ./vendor/bin/phpunit
    fi

    # Prevent the commit if some tests are failing
    if [ $? -ne 0 ]; then
        echo "\nCannot commit as some tests are failing!"
        exit 1
    fi
fi
